server:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: external-nginx
    annotations:
      kubernetes.io/ingress.class: "external-nginx"
      alb.ingress.kubernetes.io/scheme: "internet-facing"
    paths:
      - path: "/"
        pathType: Prefix
    # tls:
    #   - hosts:
    #       - argocd.${domain-name}
    #     secretName: argocd-tls

    # extraArgs:
    #   - --insecure
