# server:
#   ingress:
#     enabled: true
#     ingressClassName: external-nginx
#     annotations:
#       kubernetes.io/ingress.class: "external-nginx"
#       alb.ingress.kubernetes.io/scheme: "internet-facing"
#       cert-manager.io/cluster-issuer: "http-01-production"
#       # ingress.kubernetes.io/force-ssl-redirect: "true"

#     hosts:
#     - argocd.cloudwitches.online

#     #     # paths:
#     #     #   - path: /
#     #     #     pathType: Prefix

#     tls:
#     - hosts:
#       - argocd.cloudwitches.online
#       secretName: argocd-cloudwitches-online

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  annotations:
    kubernetes.io/ingress.class: "external-nginx"
    cert-manager.io/cluster-issuer: http-01-production
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: external-nginx
  tls:
  - hosts:
    - argocd.cloudwitches.online
    secretName: argocd-cloudwitches-online
  rules:
  - host: argocd.cloudwitches.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
