server:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: external-nginx

    annotations:
      kubernetes.io/ingress.class: external-nginx
      cert-manager.io/cluster-issuer: http-01-production
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    hosts:
      - argocd.cloudwitches.online

    paths:
      - /

    pathType: Prefix

    tls:
      - hosts:
          - argocd.cloudwitches.online
        secretName: argocd-cloudwitches-online

  extraArgs:
    - --insecure

# password generation on argocd 
# kubectl get secret -n argocd argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
